### ISSUE TITLE
Time out time?

### ISSUE THREAD

**Issue by dheerajgajula02** [tempmail-lol/api-python#5]
hello, I'm planning to use this in my personal project, what is the time-out period of the token ?
thanks

**Comment by AlexanderEpolite** [comment]
> hello, I'm planning to use this in my personal project, what is the time-out period of the token ?
> 
> thanks 

If you are using our free tier, it is 10 minutes since the last time the inbox was checked, with a hard limit of one hour where the inbox will be deleted regardless.

You can see our pricing on https://tempmail.lol/pricing.html if you would like higher limits.  Paid tiers also expire inboxes after 10 minutes since last check, but this raises the hard limit.

**Comment by AlexanderEpolite** [comment]
Hello,

Starting August 12th, the 10 minute check will be removed with the release of API v2.

**Comment by dheerajgajula02** [comment]
Thanks, appreciate it
